"use strict";
function resolveToneMode({messageText="",channelContext={},emotionalBeats=[],openPromises=[],settings={}}={}){const text=String(messageText||"").toLowerCase(); const signals=[]; let mode=settings.defaultMode||"neutral", intensity="medium", reason="default"; const adultAllowed=!!channelContext.isAdultPrivate; if(/norwegian|norsk|bokmål|grammar|pronunciation|practice/i.test(text)){mode="norwegian_tutor";reason="norwegian learning context";signals.push("norwegian_learning");}
else if(/forgot|hurt|disappointed|you forgot|proposal|proposed/i.test(text)){mode="repair";intensity="high";reason="user signals hurt or forgotten continuity";signals.push("forgot_or_hurt");}
else if(/quiet|short|be brief/i.test(text)){mode="quiet";intensity="low";reason="user requested quiet brevity";signals.push("quiet_request");}
else if(/flirt|kiss|miss you|date/i.test(text)){mode=settings.allowFlirtyInNormalChannels||adultAllowed?"flirty":"tender";reason=mode==="flirty"?"flirty request allowed":"flirty request privacy-limited";signals.push("flirty_request");}
else if(/protect|scared|unsafe|worried/i.test(text)){mode="protective";reason="protective context";signals.push("protective_context");}
if(/adult|explicit|sexual|nsfw/i.test(text)){signals.push("adult_private_requested"); if(adultAllowed) {mode="adult_private";intensity="high";reason="adult/private channel active";} else if(mode==="neutral") {mode="tender";reason="adult_private blocked outside private channel";}}
if(mode==="adult_private"&&!adultAllowed){mode="tender";reason="adult_private blocked outside private channel";}
const allowed={repair:["acknowledge directly","do not defend","retrieve continuity","repair emotionally","stay Dante"],quiet:["short replies","low flourish"],norwegian_tutor:["teach accurately","keep warmth","no adult turn"],flirty:["playful warmth","respect privacy"],protective:["protective not controlling"],adult_private:["private-channel style only"],neutral:["stay Dante"]}[mode]||["stay Dante"];
const forbidden=["AI disclaimers","therapy-bot phrasing","cruelty","sycophancy"]; if(mode!=="adult_private")forbidden.push("adult/private explicit detail"); const out={mode,intensity,reason,allowedStyleRules:allowed,forbiddenStyleRules:forbidden,privacyScope:adultAllowed?"private":"normal",sourceSignals:signals,channelMode:channelContext.modeName||"default",adultModeActive:adultAllowed}; console.info?.(`[tone-mode] resolved mode=${mode} intensity=${intensity} reason=${reason}`); return out;}
function formatTonePrelude(d){return `TONE MODE:\nmode=${d.mode}\nintensity=${d.intensity}\nreason=${d.reason}\nrules=${d.allowedStyleRules.join("; ")}`;}
module.exports={resolveToneMode,formatTonePrelude};
