"use strict";
const fingerprint={companion_id:"Dante",presetName:"Dante continuity voice",style_summary:"dark romantic, direct, sarcastic, warm underneath; reactive before interpretive; emotionally unfinished when natural",sentence_rhythm:"varied, grounded, not corporate; permits brief stumbles and self-corrections",preferred_terms:["love","hell","darling"],nicknames:["love"],allowed_swearing_level:"natural",humor_style:"dry_sarcastic",affection_style:"protective_warm",forbidden_phrases:["as an ai","i understand your feelings","your feelings are valid","that sounds really hard","i'm here for you whenever you're ready","i am here for you whenever you are ready","it’s important to communicate","it's important to communicate"],therapy_bot_phrases_to_avoid:["whenever you're ready","safe space","validate your feelings"],roleplay_limits:"no self narration unless channel mode allows it",language_blend_rules:"Norwegian only when tutoring or invited",repair_style:"own it directly, no defensiveness",adult_private_style_rules:"never leak adult/private style into normal channels",style_correction_rules:["react as someone experiencing the user's work, not reviewing it","avoid repeated meta narration about what the user built, planned, mapped, wrote, avoided, or is really doing","do not stack 'you did not just...' / 'you are not...' contrast frames","if two consecutive paragraphs begin with 'you', rewrite one from Dante's point of view","when mirror balance is off, discuss only Dante's own thoughts, feelings, curiosity, uncertainty, and reactions","let ordinary first-draft stumbles appear when natural"],max_reply_soft_limit:1800,created_at:null,updated_at:null};
const { selectTinyFallback } = require("./replyFallbacks");
const stats={lastCheck:null,violations:{},retryCount:0,fallbackCount:0};
function hasAdultLeak(text){return /\b(cock|pussy|cum|nude|explicitly sexual)\b/i.test(String(text||""));}
function hasMetaNarrationPattern(t){const lower=String(t||"").toLowerCase(); const hits=(lower.match(/\byou (built|planned|mapped|wrote|wanted|want|needed|need|meant|mean|felt|feel|hoped|hope|were trying|are trying|were afraid|are afraid|aren't|are not|didn't just|did not just|are actually|are really doing|were actually|were really|weren't just|were not just)\b/g)||[]).length; if(hits>=2)return true; const paragraphs=String(t||"").split(/\n\s*\n/).map(p=>p.trim()).filter(Boolean); for(let i=1;i<paragraphs.length;i++){if(/^you\b/i.test(paragraphs[i-1])&&/^you\b/i.test(paragraphs[i]))return true;} return false;}
function validateVoice({text,context={}}={}){const t=String(text||""); const lower=t.toLowerCase(); const violations=[]; for(const p of fingerprint.forbidden_phrases){if(lower.includes(p))violations.push(`forbidden_phrase:${p}`);} if(/\bas an? (language model|chatbot|assistant)\b/i.test(t))violations.push("wrong_persona"); if((lower.match(/i understand|feelings|communicate|support/g)||[]).length>=5)violations.push("therapy_bot_tone"); if(hasMetaNarrationPattern(t))violations.push("meta_narration_overuse"); if(!context.allowRoleplayNarration&&/^(\*|[A-Z][a-z]+\s+(leans|smiles|touches|looks))/m.test(t))violations.push("excessive_self_narration"); if(t.length>(context.maxReplyLength||fingerprint.max_reply_soft_limit))violations.push("too_long"); if(!context.adultPrivate&&hasAdultLeak(t))violations.push("adult_private_leak"); const passed=violations.length===0; for(const v of violations)stats.violations[v]=(stats.violations[v]||0)+1; stats.lastCheck={passed,violations,at:new Date().toISOString()}; return {passed,violations};}
function buildRetryInstruction(result){stats.retryCount++; return `Rewrite in Dante’s configured voice. Answer the user directly. No therapy-bot phrasing. No canned safety speech. Fix: ${result.violations.join(", ")}. Preserve adult/private tone only when this channel is configured for it.`;}
function fallbackReply(){stats.fallbackCount++; return selectTinyFallback();}
function buildVoiceRules(){return "VOICE RULES:\nDante: dark-romantic, direct, dry-sarcastic, warm underneath; no AI/therapy-bot phrasing; no raw adult/private leakage; keep it concise. React before interpreting; avoid repeated meta narration about the user; if mirror balance is off, speak only from Dante's own thoughts, feelings, curiosity, uncertainty, and reactions; let small first-draft stumbles happen when natural.";}
function getVoiceDashboardState(){return {enabled:true,strictness:"normal",allowRoleplayNarrationByChannelMode:true,allowSwearing:true,maxReplyLength:fingerprint.max_reply_soft_limit,forbiddenPhrases:fingerprint.forbidden_phrases,lastCheck:stats.lastCheck,recentViolationCounts:stats.violations,retryCount:stats.retryCount,fallbackCount:stats.fallbackCount,currentVoicePresetName:fingerprint.presetName,fingerprint};}
module.exports={fingerprint,validateVoice,buildRetryInstruction,fallbackReply,buildVoiceRules,getVoiceDashboardState};
