"use strict";
const { createPostgresPool } = require("./postgres/createPostgresPool");
function nowIso(){return new Date().toISOString();}
function expiresAt(h=2){return new Date(Date.now()+h*3600000).toISOString();}
function mapRow(r){if(!r)return null;return{id:r.id,user_scope:r.user_scope,companion_id:r.companion_id,residue_type:r.residue_type||'unknown',summary:r.summary||'',intensity:r.intensity||'medium',decay_rate:Number(r.decay_rate)||2,source_channel_id:r.source_channel_id||'',source_message_id:r.source_message_id||'',privacy_scope:r.privacy_scope||'normal',adult_context:!!r.adult_context,active:r.active!==false&&r.active!=='false',created_at:r.created_at,updated_at:r.updated_at,expires_at:r.expires_at};}
function createFallbackStore(){const rows=[];let id=1;return{available:true,async init(){},async createResidue(p){const t=nowIso();const decayH=p.decay_rate||2;const ea=p.expires_at||expiresAt(decayH);const row={id:id++,user_scope:p.user_scope,companion_id:p.companion_id,residue_type:p.residue_type||'unknown',summary:p.summary||'',intensity:p.intensity||'medium',decay_rate:decayH,source_channel_id:p.source_channel_id||'',source_message_id:p.source_message_id||'',privacy_scope:p.privacy_scope||'normal',adult_context:!!p.adult_context,active:true,created_at:t,updated_at:t,expires_at:ea};rows.push(row);return mapRow(row);},async listActiveResidue({user_scope,companion_id,include_adult=false,limit=10}){const now=new Date();return rows.filter(r=>r.user_scope===user_scope&&r.companion_id===companion_id&&r.active&&(!r.expires_at||new Date(r.expires_at)>now)&&(include_adult||!r.adult_context)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,limit).map(mapRow);},async listAll({user_scope,companion_id,limit=50}){return rows.filter(r=>r.user_scope===user_scope&&r.companion_id===companion_id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,limit).map(mapRow);},async expireStale(){const now=new Date();rows.forEach(r=>{if(r.expires_at&&new Date(r.expires_at)<now)r.active=false;});},async deactivate({id}){const r=rows.find(x=>x.id===id);if(r){r.active=false;r.updated_at=nowIso();}return mapRow(r)||null;}};}
const SQL=`CREATE TABLE IF NOT EXISTS attention_residue (id BIGSERIAL PRIMARY KEY,user_scope TEXT NOT NULL,companion_id TEXT NOT NULL,residue_type TEXT NOT NULL DEFAULT 'unknown',summary TEXT NOT NULL DEFAULT '',intensity TEXT NOT NULL DEFAULT 'medium',decay_rate REAL NOT NULL DEFAULT 2,source_channel_id TEXT NOT NULL DEFAULT '',source_message_id TEXT NOT NULL DEFAULT '',privacy_scope TEXT NOT NULL DEFAULT 'normal',adult_context BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ);`;
function createAttentionResidueStore({config,logger}={}){let pool=null;try{pool=createPostgresPool({config});}catch{}if(!pool)return createFallbackStore();return{available:true,async init(){await pool.query(SQL);await pool.query("CREATE INDEX IF NOT EXISTS ar_scope_active ON attention_residue (user_scope,companion_id,active,created_at DESC)");logger?.info?.("[attention-residue] storage initialised");},async createResidue(p){const decayH=p.decay_rate||2;const ea=p.expires_at||expiresAt(decayH);const{rows}=await pool.query(`INSERT INTO attention_residue (user_scope,companion_id,residue_type,summary,intensity,decay_rate,source_channel_id,source_message_id,privacy_scope,adult_context,active,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,$11) RETURNING *`,[p.user_scope,p.companion_id,p.residue_type||'unknown',p.summary||'',p.intensity||'medium',decayH,p.source_channel_id||'',p.source_message_id||'',p.privacy_scope||'normal',!!p.adult_context,ea]);return mapRow(rows[0]);},async listActiveResidue({user_scope,companion_id,include_adult=false,limit=10}){const{rows}=await pool.query(`SELECT * FROM attention_residue WHERE user_scope=$1 AND companion_id=$2 AND active=true AND (expires_at IS NULL OR expires_at > NOW())${include_adult?'':' AND adult_context=false'} ORDER BY created_at DESC LIMIT $3`,[user_scope,companion_id,limit]);return rows.map(mapRow);},async listAll({user_scope,companion_id,limit=50}){const{rows}=await pool.query('SELECT * FROM attention_residue WHERE user_scope=$1 AND companion_id=$2 ORDER BY created_at DESC LIMIT $3',[user_scope,companion_id,limit]);return rows.map(mapRow);},async expireStale(){await pool.query('UPDATE attention_residue SET active=false,updated_at=NOW() WHERE active=true AND expires_at IS NOT NULL AND expires_at < NOW()');},async deactivate({id}){const{rows}=await pool.query('UPDATE attention_residue SET active=false,updated_at=NOW() WHERE id=$1 RETURNING *',[id]);return mapRow(rows[0])||null;}};}
module.exports={createAttentionResidueStore};
