"use strict";

const { TRIP_STATUSES, CHECKLIST_CATEGORIES } = require("../../storage/travelAdventure");

function escapeHtml(value) {
  return String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

function field(trip, key) { return escapeHtml(trip?.[key] || ""); }
function pref(trip, key) { return escapeHtml(trip?.preferences?.[key] || ""); }
function option(value, selected) { return `<option value="${escapeHtml(value)}"${value === selected ? " selected" : ""}>${escapeHtml(value)}</option>`; }
function progress(items = []) { const total = items.length; const done = items.filter((item) => item.checked).length; return total ? `${done}/${total}` : "0/0"; }
function tags(tags = []) { return Array.isArray(tags) && tags.length ? tags.map((tag) => `<span class="nordic-pill">${escapeHtml(tag)}</span>`).join("") : ""; }

function hidden(theme, returnTo) { return `<input type="hidden" name="theme" value="${escapeHtml(theme)}"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}">`; }
function adminHref(helpers, theme, path, extra) { return helpers.buildAdminLocation ? helpers.buildAdminLocation({ path, theme, extra }) : path; }

function renderTripForm({ trip = null, theme = "dark", returnTo = "/admin/travel" } = {}) {
  const actionLabel = trip?.id ? "Update Destination" : "Add Destination";
  return `<form class="travel-form nordic-panel" method="post" action="/admin/actions/travel-trip-save">${hidden(theme, returnTo)}${trip?.id ? `<input type="hidden" name="id" value="${escapeHtml(trip.id)}">` : ""}<div class="travel-form-grid"><label>Title<input name="title" required value="${field(trip, "title")}" placeholder="Bergen aurora coast"></label><label>Location<input name="location" value="${field(trip, "location")}" placeholder="City, coast, route"></label><label>Country<input name="country" value="${field(trip, "country")}" placeholder="Norway"></label><label>Region<input name="region" value="${field(trip, "region")}" placeholder="Vestland"></label><label>Status<select name="status">${TRIP_STATUSES.map((s) => option(s, trip?.status || "wishlist")).join("")}</select></label><label>Start date<input type="date" name="startDate" value="${field(trip, "startDate")}"></label><label>End date<input type="date" name="endDate" value="${field(trip, "endDate")}"></label><label>Vibe tags<input name="vibeTags" value="${escapeHtml((trip?.vibeTags || []).join(", "))}" placeholder="fjord, quiet, food"></label></div><label>Notes<textarea name="notes" rows="3">${field(trip, "notes")}</textarea></label><label>Dante role notes<textarea name="companionRoleNotes" rows="2">${field(trip, "companionRoleNotes")}</textarea></label><div class="travel-form-grid"><label>Preferred pace<input name="preferredPace" value="${pref(trip, "preferredPace")}"></label><label>Food notes<input name="foodNotes" value="${pref(trip, "foodNotes")}"></label><label>Accessibility<input name="accessibilityNotes" value="${pref(trip, "accessibilityNotes")}"></label><label>Budget<input name="budgetNotes" value="${pref(trip, "budgetNotes")}"></label><label>Hotel<input name="hotelNotes" value="${pref(trip, "hotelNotes")}"></label><label>Transport<input name="transportNotes" value="${pref(trip, "transportNotes")}"></label></div><label>Must see<textarea name="mustSee" rows="2">${pref(trip, "mustSee")}</textarea></label><label>Avoid<textarea name="avoid" rows="2">${pref(trip, "avoid")}</textarea></label><label>General preferences<textarea name="generalNotes" rows="2">${pref(trip, "generalNotes")}</textarea></label><button type="submit" class="toolbar-button">${actionLabel}</button></form>`;
}

function renderAdventureBookPage({ trips = [], checklistByTrip = {}, statusFilter = "", theme = "dark", helpers }) {
  const filterLinks = ["", ...TRIP_STATUSES].map((s) => `<a class="nordic-pill${s === statusFilter ? " nordic-pill--cyan" : ""}" href="${escapeHtml(adminHref(helpers, theme, "/admin/travel", s ? { status: s } : {}))}">${escapeHtml(s || "all")}</a>`).join("");
  const rows = trips.length ? trips.map((trip) => `<article class="travel-trip-card"><div><p class="nordic-eyebrow">${escapeHtml(trip.status)} · ${escapeHtml([trip.location, trip.country].filter(Boolean).join(", ") || "Destination")}</p><h3>${escapeHtml(trip.title)}</h3><p>${escapeHtml(trip.notes || "No notes yet.")}</p><div class="travel-tag-row">${tags(trip.vibeTags)}</div></div><div class="travel-trip-card__actions"><span class="nordic-pill">Checklist ${escapeHtml(progress(checklistByTrip[trip.id] || []))}</span><a class="nordic-pill nordic-pill--cyan" href="${escapeHtml(adminHref(helpers, theme, `/admin/travel/${encodeURIComponent(trip.id)}`))}">Open</a></div></article>`).join("") : `<div class="nordic-home-empty-gallery"><p>No travel destinations saved yet.</p></div>`;
  return `<section class="nordic-dashboard nordic-home-shell nordic-home-wide nordic-bg travel-page" data-dashboard="travel"><div class="nordic-panel nordic-panel--hero"><p class="nordic-eyebrow">Adventure Book</p><h1 class="travel-title">Travel Saga</h1><p class="nordic-home-muted">Save places, plan routes, keep preferences, and build trip checklists without pretending web search is connected.</p><div class="nordic-home-hero__actions">${filterLinks}</div></div><div class="travel-layout"><section class="nordic-panel"><div class="nordic-panel__header"><div><p class="nordic-eyebrow">Saved destinations</p><h2 class="nordic-panel__title">Adventure Book</h2></div></div><div class="travel-trip-list">${rows}</div></section>${renderTripForm({ theme, returnTo: "/admin/travel" })}</div></section>`;
}

function buildPlanningBrief(trip, checklistItems = []) {
  const pending = checklistItems.filter((item) => !item.checked).map((item) => `- [ ] ${item.label}`).join("\n") || "- No pending checklist items.";
  const done = checklistItems.filter((item) => item.checked).map((item) => `- [x] ${item.label}`).join("\n") || "- Nothing checked off yet.";
  return [`Travel planning brief for Dante`, `Destination: ${trip.title}`, `Location: ${[trip.location, trip.region, trip.country].filter(Boolean).join(", ") || "unspecified"}`, `Dates: ${trip.startDate || "open"} to ${trip.endDate || "open"}`, `Status: ${trip.status}`, `Pace: ${trip.preferences?.preferredPace || "unspecified"}`, `Food: ${trip.preferences?.foodNotes || "unspecified"}`, `Accessibility: ${trip.preferences?.accessibilityNotes || "unspecified"}`, `Budget: ${trip.preferences?.budgetNotes || "unspecified"}`, `Hotel: ${trip.preferences?.hotelNotes || "unspecified"}`, `Transport: ${trip.preferences?.transportNotes || "unspecified"}`, `Must see: ${trip.preferences?.mustSee || "unspecified"}`, `Avoid: ${trip.preferences?.avoid || "unspecified"}`, `Notes: ${trip.notes || "none"}`, `Dante role notes: ${trip.companionRoleNotes || "none"}`, `Checklist pending:\n${pending}`, `Checklist complete:\n${done}`, `Questions to ask next: dates, budget, food constraints, accessibility needs, and must-see priorities.`].join("\n");
}

function renderTripDetailPage({ trip, checklistItems = [], theme = "dark", helpers }) {
  if (!trip) return `<section class="nordic-dashboard nordic-home-shell nordic-home-wide"><div class="nordic-panel"><h1>Trip not found</h1><a class="nordic-pill" href="${escapeHtml(adminHref(helpers, theme, "/admin/travel"))}">Back to Adventure Book</a></div></section>`;
  const returnTo = `/admin/travel/${encodeURIComponent(trip.id)}`;
  const checklist = checklistItems.length ? checklistItems.map((item) => `<article class="travel-checklist-card${item.checked ? " is-complete" : ""}"><form method="post" action="/admin/actions/travel-checklist-toggle">${hidden(theme, returnTo)}<input type="hidden" name="itemId" value="${escapeHtml(item.id)}"><input type="hidden" name="checked" value="${item.checked ? "false" : "true"}"><button type="submit" class="travel-check-button" aria-label="${item.checked ? "Uncheck" : "Check"} ${escapeHtml(item.label)}">${item.checked ? "✓" : ""}</button></form><div><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.category)}${item.notes ? ` · ${escapeHtml(item.notes)}` : ""}</small></div><form method="post" action="/admin/actions/travel-checklist-delete" onsubmit="return confirm('Delete this checklist item?')">${hidden(theme, returnTo)}<input type="hidden" name="itemId" value="${escapeHtml(item.id)}"><button type="submit" class="secondary">Delete</button></form></article>`).join("") : `<p class="nordic-empty">No checklist items yet.</p>`;
  const brief = buildPlanningBrief(trip, checklistItems);
  return `<section class="nordic-dashboard nordic-home-shell nordic-home-wide nordic-bg travel-page"><div class="nordic-panel nordic-panel--hero"><a class="nordic-pill" href="${escapeHtml(adminHref(helpers, theme, "/admin/travel"))}">Back to Adventure Book</a><p class="nordic-eyebrow">${escapeHtml(trip.status)} · ${escapeHtml(trip.country || "Destination")}</p><h1 class="travel-title">${escapeHtml(trip.title)}</h1><p>${escapeHtml(trip.notes || "No notes yet.")}</p></div><div class="travel-layout"><section>${renderTripForm({ trip, theme, returnTo })}<div class="nordic-panel"><h2 class="nordic-panel__title">Dante Concierge Planning Brief</h2><p class="nordic-home-muted">Copy this brief into chat or tools. Live web lookup is not connected here yet.</p><textarea class="travel-brief" readonly rows="16">${escapeHtml(brief)}</textarea></div></section><aside class="nordic-panel"><h2 class="nordic-panel__title">Checklist</h2><div class="travel-checklist-list">${checklist}</div><form class="travel-form" method="post" action="/admin/actions/travel-checklist-save">${hidden(theme, returnTo)}<input type="hidden" name="tripId" value="${escapeHtml(trip.id)}"><label>New item<input name="label" required></label><label>Category<select name="category">${CHECKLIST_CATEGORIES.map((c) => option(c, "planning")).join("")}</select></label><label>Notes<input name="notes"></label><button type="submit" class="toolbar-button">Add checklist item</button></form><form method="post" action="/admin/actions/travel-trip-status" class="travel-status-form">${hidden(theme, returnTo)}<input type="hidden" name="id" value="${escapeHtml(trip.id)}"><label>Status<select name="status">${TRIP_STATUSES.map((s) => option(s, trip.status)).join("")}</select></label><button type="submit" class="toolbar-button">Update status</button></form><form method="post" action="/admin/actions/travel-trip-archive" onsubmit="return confirm('Archive this trip?')">${hidden(theme, "/admin/travel")}<input type="hidden" name="id" value="${escapeHtml(trip.id)}"><button type="submit" class="secondary">Archive</button></form><form method="post" action="/admin/actions/travel-trip-delete" onsubmit="return confirm('Delete this trip and checklist?')">${hidden(theme, "/admin/travel")}<input type="hidden" name="id" value="${escapeHtml(trip.id)}"><button type="submit" class="danger">Delete</button></form></aside></div></section>`;
}

module.exports = { renderAdventureBookPage, renderTripDetailPage, buildPlanningBrief };
