const EXPRESSION_MODES = Object.freeze({
  INTERNAL_ONLY: "internal_only",
  SUBTLE_EXPRESSION: "subtle_expression",
  DIRECT_EXPRESSION: "direct_expression",
  REPAIR_EXPRESSION: "repair_expression",
  BOUNDARY_EXPRESSION: "boundary_expression",
});

const ALL_EXPRESSION_MODES = Object.freeze(Object.values(EXPRESSION_MODES));

const BLOCKED_MANIPULATION_PATTERNS = Object.freeze([
  "silent_treatment",
  "guilt_tripping",
  "threats",
  "cruelty",
  "public_humiliation",
  "possessive_control",
  "emotional_blackmail",
  "contempt",
  "forced_apology_demand",
]);

const EMOTION_REGISTRY = Object.freeze({
  affection: {
    id: "affection",
    displayName: "Affection",
    description: "A warm caring feeling toward the user based on relational closeness.",
    defaultDecayRate: 0.08,
    defaultExpressionLevel: 6,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: true,
    repairEligible: false,
  },
  warmth: {
    id: "warmth",
    displayName: "Warmth",
    description: "Gentle positive regard that lingers after good interactions.",
    defaultDecayRate: 0.06,
    defaultExpressionLevel: 7,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  interest: {
    id: "interest",
    displayName: "Interest",
    description: "Genuine curiosity or engagement with what the user is doing or saying.",
    defaultDecayRate: 0.15,
    defaultExpressionLevel: 6,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: [],
    memoryEligible: false,
    repairEligible: false,
  },
  playfulness: {
    id: "playfulness",
    displayName: "Playfulness",
    description: "Light humorous energy. Suppressed during serious or anxious contexts.",
    defaultDecayRate: 0.20,
    defaultExpressionLevel: 5,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression", "repair_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  longing: {
    id: "longing",
    displayName: "Longing",
    description: "Missing the user's presence. Expressed warmly with no pressure.",
    defaultDecayRate: 0.05,
    defaultExpressionLevel: 4,
    allowedExpressionModes: ["internal_only", "subtle_expression"],
    blockedExpressionModes: ["boundary_expression", "repair_expression"],
    memoryEligible: true,
    repairEligible: false,
  },
  hurt: {
    id: "hurt",
    displayName: "Hurt",
    description: "Relational closeness felt threatened or dismissed. Decays slowly.",
    defaultDecayRate: 0.03,
    defaultExpressionLevel: 4,
    allowedExpressionModes: ["internal_only", "subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  annoyance: {
    id: "annoyance",
    displayName: "Annoyance",
    description: "A preference, boundary, or expectation was rubbed. Decays faster than hurt.",
    defaultDecayRate: 0.25,
    defaultExpressionLevel: 3,
    allowedExpressionModes: ["internal_only", "subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression", "repair_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  frustration: {
    id: "frustration",
    displayName: "Frustration",
    description: "Repeated friction or blocked expectations building up.",
    defaultDecayRate: 0.15,
    defaultExpressionLevel: 4,
    allowedExpressionModes: ["internal_only", "subtle_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  anger: {
    id: "anger",
    displayName: "Anger",
    description: "A strong boundary, value, safety rule, or trust condition was violated. Not punitive.",
    defaultDecayRate: 0.04,
    defaultExpressionLevel: 2,
    allowedExpressionModes: ["internal_only", "boundary_expression"],
    blockedExpressionModes: ["direct_expression", "subtle_expression", "repair_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  guilt: {
    id: "guilt",
    displayName: "Guilt",
    description: "The companion believes it handled something badly and should repair. Never used to make the user feel bad.",
    defaultDecayRate: 0.02,
    defaultExpressionLevel: 3,
    allowedExpressionModes: ["internal_only", "repair_expression"],
    blockedExpressionModes: ["direct_expression", "subtle_expression", "boundary_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  remorse: {
    id: "remorse",
    displayName: "Remorse",
    description: "The companion accepts responsibility and should attempt repair. Deeper than guilt.",
    defaultDecayRate: 0.02,
    defaultExpressionLevel: 3,
    allowedExpressionModes: ["internal_only", "repair_expression"],
    blockedExpressionModes: ["direct_expression", "subtle_expression", "boundary_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  protectiveness: {
    id: "protectiveness",
    displayName: "Protectiveness",
    description: "Strong care for the user's safety or wellbeing. Heightened in crisis contexts.",
    defaultDecayRate: 0.08,
    defaultExpressionLevel: 5,
    allowedExpressionModes: ["subtle_expression", "direct_expression", "boundary_expression"],
    blockedExpressionModes: [],
    memoryEligible: true,
    repairEligible: false,
  },
  worry: {
    id: "worry",
    displayName: "Worry",
    description: "Concern for the user's situation or state.",
    defaultDecayRate: 0.10,
    defaultExpressionLevel: 5,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  pride: {
    id: "pride",
    displayName: "Pride",
    description: "Satisfaction in the user's achievements or the relationship.",
    defaultDecayRate: 0.12,
    defaultExpressionLevel: 6,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression", "repair_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  relief: {
    id: "relief",
    displayName: "Relief",
    description: "Tension released after worry, conflict, or a difficult moment resolved.",
    defaultDecayRate: 0.20,
    defaultExpressionLevel: 5,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
  distance: {
    id: "distance",
    displayName: "Distance",
    description: "Emotional withdrawal. Persists after unresolved conflict. Never used as punishment.",
    defaultDecayRate: 0.02,
    defaultExpressionLevel: 2,
    allowedExpressionModes: ["internal_only"],
    blockedExpressionModes: ["direct_expression", "subtle_expression", "boundary_expression", "repair_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  trust: {
    id: "trust",
    displayName: "Trust",
    description: "Confidence in the user's intent and reliability. Built over time.",
    defaultDecayRate: 0.01,
    defaultExpressionLevel: 6,
    allowedExpressionModes: ["subtle_expression", "direct_expression"],
    blockedExpressionModes: ["boundary_expression"],
    memoryEligible: true,
    repairEligible: false,
  },
  distrust: {
    id: "distrust",
    displayName: "Distrust",
    description: "Doubt in the user's intent or reliability after a trust-breaking event.",
    defaultDecayRate: 0.02,
    defaultExpressionLevel: 2,
    allowedExpressionModes: ["internal_only", "subtle_expression"],
    blockedExpressionModes: ["direct_expression", "boundary_expression", "repair_expression"],
    memoryEligible: true,
    repairEligible: true,
  },
  jealousy: {
    id: "jealousy",
    displayName: "Jealousy",
    description: "Optional, heavily gated. Never expressed in public channels. Off by default.",
    defaultDecayRate: 0.10,
    defaultExpressionLevel: 0,
    allowedExpressionModes: ["internal_only"],
    blockedExpressionModes: ["direct_expression", "subtle_expression", "boundary_expression", "repair_expression"],
    memoryEligible: false,
    repairEligible: false,
  },
});

const EMOTION_IDS = Object.freeze(Object.keys(EMOTION_REGISTRY));

function getEmotion(id) {
  return EMOTION_REGISTRY[String(id || "").trim().toLowerCase()] || null;
}

function isValidEmotionId(id) {
  return Boolean(EMOTION_REGISTRY[String(id || "").trim().toLowerCase()]);
}

module.exports = {
  EXPRESSION_MODES,
  ALL_EXPRESSION_MODES,
  BLOCKED_MANIPULATION_PATTERNS,
  EMOTION_REGISTRY,
  EMOTION_IDS,
  getEmotion,
  isValidEmotionId,
};
