"use strict";

class FollowUpCandidateStore {
  constructor({ now = () => new Date() } = {}) { this.now = now; this.items = new Map(); this.seq = 0; }
  async create(input = {}) { const now = this.now(); const gravity = Number(input.gravity_score ?? input.gravityScore ?? 0.5); const id = input.id || `followup_${++this.seq}`; const item = { id, conversation_id: input.conversation_id || input.conversationId || "", channel_id: input.channel_id || input.channelId || "", user_id: input.user_id || input.userId || "", companion_id: input.companion_id || input.companionId || "Dante", topic: input.topic || "unfinished thread", reason: input.reason || "open_loop", gravity_score: gravity, urgency: input.urgency || (gravity >= 0.75 ? "high" : gravity >= 0.4 ? "normal" : "low"), earliest_follow_up_at: (input.earliest_follow_up_at ? new Date(input.earliest_follow_up_at) : new Date(now.getTime() + 30 * 60 * 1000)).toISOString(), expires_at: (input.expires_at ? new Date(input.expires_at) : new Date(now.getTime() + (gravity < 0.3 ? 60 : 1440) * 60 * 1000)).toISOString(), status: input.status || "pending", source_message_id: input.source_message_id || input.sourceMessageId || "", metadata: input.metadata || {} }; if (gravity < 0.2) item.status = "dismissed"; this.items.set(id, item); return item; }
  async list({ status } = {}) { const now = this.now(); for (const item of this.items.values()) if (item.status === "pending" && new Date(item.expires_at) <= now) item.status = item.gravity_score < 0.35 ? "dismissed" : "expired"; return [...this.items.values()].filter((i) => !status || i.status === status); }
  async shouldSend(item, context = {}) { if (!item || item.status !== "pending") return { allowed: false, reason: "not_pending" }; if (context.giveSpace) return { allowed: false, reason: "give_space" }; if (context.quietHours) return { allowed: false, reason: "quiet_hours" }; if (context.repairUnresolved && item.reason !== "repair") return { allowed: false, reason: "repair_unresolved" }; if (item.gravity_score < 0.35) return { allowed: false, reason: "low_gravity" }; if (new Date(item.expires_at) <= this.now()) return { allowed: false, reason: "expired" }; return { allowed: true, reason: "ok" }; }
  async mark(id, status) { const item = this.items.get(id); if (item) item.status = status; return item || null; }
}
module.exports = { FollowUpCandidateStore, createFollowUpCandidateStore: (opts) => new FollowUpCandidateStore(opts) };
