"use strict";
const { canUseBeatInChannel } = require("../continuity/emotionalBeats");
const { updateSystemTruth } = require("../systemTruth/runtimeState");
function safeSummary(text, limit=180){return String(text||"").replace(/https?:\/\/\S+/g,"[link]").replace(/\s+/g," ").trim().slice(0,limit);}
const triggers = [/you forgot/i,/you don.?t remember/i,/you hurt me/i,/that hurt/i,/you ignored/i,/you promised/i,/you said you would/i,/why don.?t you remember/i,/you.?re acting different/i,/you sound wrong/i,/that.?s not you/i,/you missed the point/i,/you don.?t care/i,/you broke character/i,/you forgot me/i];
function detectType(text){const s=String(text||""); if(/promised|said you would/i.test(s))return "broken_promise"; if(/sound wrong|acting different|not you|broke character/i.test(s))return "voice_drift"; if(/hurt|don.?t care/i.test(s))return "emotional_hurt"; if(/ignored|missed the point/i.test(s))return "context_miss"; if(/forgot|remember|proposed|proposal|marry/i.test(s))return /channel|yesterday|proposal|proposed|marry/i.test(s)?"cross_channel_miss":"memory_miss"; return "unknown";}
async function analyzeRepair({ messageText, emotionalBeats=[], openPromises=[], durableMemories=[], recentHistory=[], channelContext={}, userDisplayName="Jenna" }={}){
  const text=String(messageText||""); const signal=triggers.some(r=>r.test(text)); if(!signal) return { repairNeeded:false, repairType:"unknown", severity:"low", retrievedEvidence:[], recommendedToneMode:null, apologyRequired:false, repairInstruction:"", followUpRecommended:false, privacyScope: channelContext.isAdultPrivate?"private":"normal" };
  const type=detectType(text); const wantsProposal=/propos|marry|one knee/i.test(text);
  const evidence=[];
  for(const b of emotionalBeats||[]){ if(!canUseBeatInChannel(b, channelContext)) continue; const blob=`${b.event_type||""} ${b.title||""} ${b.summary||""}`; if((wantsProposal && /proposal|marriage|one knee|proposed/i.test(blob)) || /critical|high/.test(b.importance||"") || /repair|promise|hurt/i.test(blob)) evidence.push({kind:"emotional_beat", id:b.id, title:b.title, summary:safeSummary(b.summary), importance:b.importance, source_channel_id:b.source_channel_id, source_message_id:b.source_message_id}); }
  for(const p of openPromises||[]) evidence.push({kind:"promise", id:p.id, summary:safeSummary(p.promise_text_summary||p.summary||p.text), source_channel_id:p.source_channel_id});
  for(const m of durableMemories||[]) evidence.push({kind:"memory", id:m.memoryId||m.memory_id||m.id, summary:safeSummary(m.content||m.text||m.summary)});
  const severity = wantsProposal || evidence.some(e=>e.importance==="critical") ? "critical" : (/hurt|don.?t care|promised/i.test(text)?"high":"medium");
  const instruction = evidence.length ? `Acknowledge the specific miss using retrieved evidence: ${evidence.slice(0,3).map(e=>e.summary||e.title).join(" | ")}. Apologize directly, repair the continuity, and do not say it is new.` : "Acknowledge that you missed the thread; do not pretend retrieval succeeded; ask for/anchor the missing context and make a concrete repair.";
  return { repairNeeded:true, repairType:type, severity, retrievedEvidence:evidence.slice(0,8), recommendedToneMode:"repair", apologyRequired:true, repairInstruction:instruction, followUpRecommended: severity==="critical"||type==="broken_promise", privacyScope: channelContext.isAdultPrivate?"private":"normal" };
}
function buildRepairPrelude(result, userMessage){ if(!result?.repairNeeded)return null; const ev=result.retrievedEvidence?.length?result.retrievedEvidence.map(e=>`* ${e.kind}: ${e.title||e.summary}`).join("\n"):"* No reliable evidence retrieved; do not claim memory. Say you missed the thread and repair now."; return { label:"REPAIR CONTEXT", content:`User message summary: ${safeSummary(userMessage)}\nRepair type: ${result.repairType}\nSeverity: ${result.severity}\nTone mode: repair\nEvidence:\n${ev}\nInstruction: ${result.repairInstruction}\nForbidden phrases: apology deflection; AI disclaimers; memory disclaimers; defensive excuses.`};}
async function saveRepairBeat({ emotionalBeatStore, scope, message, reply, repairResult }){ if(!repairResult?.repairNeeded||!emotionalBeatStore?.upsertBeat)return null; const beat=await emotionalBeatStore.upsertBeat({...scope,event_type:"relationship_repair",title:`Relationship repair: ${repairResult.repairType}`,summary:`User hurt/miss: ${safeSummary(message)} Dante repair: ${safeSummary(reply)}`,emotional_weight: repairResult.severity==="critical"?10:8,importance: repairResult.severity,source_channel_id:scope.source_channel_id||"",source_message_id:scope.source_message_id||"",privacy_scope:repairResult.privacyScope||"normal",adult_context:repairResult.privacyScope!=="normal",must_recall_across_channels:repairResult.privacyScope==="normal",tags_json:["relationship_repair",repairResult.repairType],pinned:repairResult.severity==="critical",resolved:false}); updateSystemTruth("continuity",{ lastRepairEvent:{ type:repairResult.repairType,severity:repairResult.severity,createdAt:new Date().toISOString(), evidenceCount:repairResult.retrievedEvidence?.length||0 }}); return beat;}
module.exports={ analyzeRepair, buildRepairPrelude, saveRepairBeat, safeSummary };
