"use strict";

// Ordered list of every table the bot owns.
// Foreign-key parents must appear before their children.
const SCHEMA_REGISTRY = [
  {
    table: "app_settings",
    sql: `CREATE TABLE IF NOT EXISTS app_settings (
  setting_key TEXT PRIMARY KEY,
  setting_value JSONB NOT NULL DEFAULT 'null'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "conversation_events",
    sql: `CREATE TABLE IF NOT EXISTS conversation_events (
  id BIGSERIAL PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  thread_id TEXT,
  channel_id TEXT NOT NULL,
  guild_id TEXT,
  discord_message_id TEXT,
  author_id TEXT,
  author_name TEXT,
  role TEXT NOT NULL,
  source TEXT NOT NULL,
  event_type TEXT NOT NULL,
  content_text TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "memories",
    sql: `CREATE TABLE IF NOT EXISTS memories (
  id BIGSERIAL PRIMARY KEY,
  memory_id UUID NOT NULL UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  domain TEXT NOT NULL,
  sensitivity TEXT NOT NULL,
  source TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  importance INTEGER NOT NULL,
  user_scope TEXT NOT NULL,
  reference_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  use_count INTEGER NOT NULL DEFAULT 0
)`,
  },
  {
    table: "memory_usage_events",
    sql: `CREATE TABLE IF NOT EXISTS memory_usage_events (
  id BIGSERIAL PRIMARY KEY,
  memory_id UUID NOT NULL REFERENCES memories(memory_id) ON DELETE CASCADE,
  user_scope TEXT NOT NULL,
  used_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "staged_memories",
    sql: `CREATE TABLE IF NOT EXISTS staged_memories (
  id BIGSERIAL PRIMARY KEY,
  staged_memory_id UUID NOT NULL UNIQUE,
  source_kind TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  grouping_key TEXT NOT NULL,
  dedupe_key TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  domain TEXT NOT NULL,
  sensitivity TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'proposed',
  review_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  promoted_memory_id UUID,
  user_scope TEXT NOT NULL,
  reference_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
)`,
  },
  {
    table: "generated_images",
    sql: `CREATE TABLE IF NOT EXISTS generated_images (
  id BIGSERIAL PRIMARY KEY,
  image_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  source_surface TEXT NOT NULL,
  conversation_id TEXT,
  channel_id TEXT,
  discord_message_id TEXT,
  prompt TEXT NOT NULL,
  composed_prompt TEXT NOT NULL,
  style_preset_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  appearance_preset_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  model TEXT NOT NULL,
  aspect_ratio TEXT,
  mime_type TEXT NOT NULL,
  file_size_bytes INTEGER NOT NULL DEFAULT 0,
  storage_key TEXT NOT NULL UNIQUE,
  thumbnail_storage_key TEXT,
  custom_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
)`,
  },
  {
    table: "generated_audio",
    sql: `CREATE TABLE IF NOT EXISTS generated_audio (
  id BIGSERIAL PRIMARY KEY,
  audio_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  source_surface TEXT NOT NULL,
  display_name TEXT NOT NULL,
  conversation_id TEXT,
  channel_id TEXT,
  discord_message_id TEXT,
  source_message_id TEXT,
  prompt TEXT NOT NULL,
  spoken_text TEXT NOT NULL,
  caption TEXT NOT NULL DEFAULT '',
  voice_id TEXT NOT NULL,
  model TEXT NOT NULL,
  output_format TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  file_size_bytes INTEGER NOT NULL DEFAULT 0,
  storage_key TEXT NOT NULL UNIQUE,
  custom_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL,
  error_message TEXT,
  provider TEXT NOT NULL DEFAULT 'elevenlabs',
  provider_voice_id TEXT,
  provider_model_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
)`,
  },
  {
    table: "music_spotify_connections",
    sql: `CREATE TABLE IF NOT EXISTS music_spotify_connections (
  user_scope TEXT PRIMARY KEY,
  spotify_user_id TEXT NOT NULL DEFAULT '',
  spotify_display_name TEXT NOT NULL DEFAULT '',
  refresh_token TEXT NOT NULL DEFAULT '',
  access_token TEXT NOT NULL DEFAULT '',
  token_expires_at TIMESTAMPTZ,
  scope TEXT NOT NULL DEFAULT '',
  oauth_state TEXT NOT NULL DEFAULT '',
  oauth_state_created_at TIMESTAMPTZ,
  connected_at TIMESTAMPTZ,
  last_import_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "music_tracks",
    sql: `CREATE TABLE IF NOT EXISTS music_tracks (
  id BIGSERIAL PRIMARY KEY,
  music_track_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  spotify_track_id TEXT NOT NULL,
  spotify_uri TEXT NOT NULL,
  spotify_url TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  artists JSONB NOT NULL DEFAULT '[]'::jsonb,
  album_name TEXT NOT NULL DEFAULT '',
  album_release_date TEXT NOT NULL DEFAULT '',
  album_release_date_precision TEXT NOT NULL DEFAULT '',
  release_year INTEGER,
  artist_genres JSONB NOT NULL DEFAULT '[]'::jsonb,
  genre_families JSONB NOT NULL DEFAULT '[]'::jsonb,
  user_genres JSONB NOT NULL DEFAULT '[]'::jsonb,
  musicbrainz_recording_id TEXT NOT NULL DEFAULT '',
  musicbrainz_release_id TEXT NOT NULL DEFAULT '',
  musicbrainz_release_group_id TEXT NOT NULL DEFAULT '',
  musicbrainz_match_confidence REAL,
  musicbrainz_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  musicbrainz_enrichment_status TEXT NOT NULL DEFAULT 'pending',
  musicbrainz_last_error TEXT NOT NULL DEFAULT '',
  musicbrainz_enriched_at TIMESTAMPTZ,
  musicbrainz_next_fetch_after TIMESTAMPTZ,
  embedding_dirty_at TIMESTAMPTZ,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  explicit BOOLEAN NOT NULL DEFAULT FALSE,
  liked_at TIMESTAMPTZ,
  source TEXT NOT NULL DEFAULT 'spotify_liked',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  imported_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, spotify_track_id)
)`,
  },
  {
    table: "music_track_affinities",
    sql: `CREATE TABLE IF NOT EXISTS music_track_affinities (
  id BIGSERIAL PRIMARY KEY,
  affinity_id UUID NOT NULL UNIQUE,
  music_track_id UUID NOT NULL REFERENCES music_tracks(music_track_id) ON DELETE CASCADE,
  user_scope TEXT NOT NULL,
  actor_key TEXT NOT NULL,
  actor_type TEXT NOT NULL,
  actor_display_name TEXT NOT NULL,
  reaction TEXT NOT NULL,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (music_track_id, actor_key)
)`,
  },
  {
    table: "music_playlists",
    sql: `CREATE TABLE IF NOT EXISTS music_playlists (
  id BIGSERIAL PRIMARY KEY,
  music_playlist_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  spotify_playlist_id TEXT NOT NULL,
  spotify_uri TEXT NOT NULL DEFAULT '',
  spotify_url TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'ai_curated',
  prompt TEXT NOT NULL DEFAULT '',
  created_by_actor_key TEXT NOT NULL DEFAULT '',
  created_by_actor_type TEXT NOT NULL DEFAULT 'ai',
  created_by_display_name TEXT NOT NULL DEFAULT '',
  track_count INTEGER NOT NULL DEFAULT 0,
  discovery_track_count INTEGER NOT NULL DEFAULT 0,
  cover_image_id TEXT NOT NULL DEFAULT '',
  spotify_cover_url TEXT NOT NULL DEFAULT '',
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  user_note TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, spotify_playlist_id)
)`,
  },
  {
    table: "music_playlist_tracks",
    sql: `CREATE TABLE IF NOT EXISTS music_playlist_tracks (
  id BIGSERIAL PRIMARY KEY,
  music_playlist_id UUID NOT NULL REFERENCES music_playlists(music_playlist_id) ON DELETE CASCADE,
  music_track_id UUID NOT NULL REFERENCES music_tracks(music_track_id) ON DELETE CASCADE,
  spotify_track_id TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT '',
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (music_playlist_id, spotify_track_id),
  UNIQUE (music_playlist_id, position)
)`,
  },
  {
    table: "cache",
    sql: `CREATE TABLE IF NOT EXISTS cache (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  cache_key TEXT NOT NULL,
  cache_value JSONB NOT NULL DEFAULT 'null'::jsonb,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, cache_key)
)`,
  },
  {
    table: "summary_queue",
    sql: `CREATE TABLE IF NOT EXISTS summary_queue (
  id BIGSERIAL PRIMARY KEY,
  queue_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  queue_type TEXT NOT NULL,
  summary_date DATE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  source_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  weekly_memory_id TEXT,
  consumed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, queue_type, summary_date)
)`,
  },
  {
    table: "journal_entries",
    sql: `CREATE TABLE IF NOT EXISTS journal_entries (
  id BIGSERIAL PRIMARY KEY,
  entry_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  automation_id UUID,
  channel_id TEXT,
  guild_id TEXT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "channel_mode_definitions",
    sql: `CREATE TABLE IF NOT EXISTS channel_mode_definitions (
  mode_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  instructions TEXT NOT NULL DEFAULT '',
  chat_model TEXT NOT NULL DEFAULT '',
  memory_types TEXT NOT NULL DEFAULT '',
  memory_sensitivity TEXT NOT NULL DEFAULT 'high',
  include_time_context TEXT NOT NULL DEFAULT 'inherit',
  retrieval_source TEXT NOT NULL DEFAULT 'off',
  retrieval_access TEXT NOT NULL DEFAULT 'off',
  heartbeat_role TEXT NOT NULL DEFAULT '',
  is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "channel_mode_assignments",
    sql: `CREATE TABLE IF NOT EXISTS channel_mode_assignments (
  guild_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  mode_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (guild_id, channel_id)
)`,
  },
  {
    table: "automations",
    sql: `CREATE TABLE IF NOT EXISTS automations (
  id BIGSERIAL PRIMARY KEY,
  automation_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  type TEXT NOT NULL,
  label TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  schedule_time TEXT NOT NULL,
  timezone TEXT NOT NULL,
  prompt TEXT NOT NULL DEFAULT '',
  enabled_tools TEXT NOT NULL DEFAULT '',
  thread_title_template TEXT NOT NULL DEFAULT '',
  thread_starter_prompt TEXT NOT NULL DEFAULT '',
  thread_mode_key TEXT NOT NULL DEFAULT 'daily',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  mention_user BOOLEAN NOT NULL DEFAULT FALSE,
  user_id TEXT,
  last_run_at TIMESTAMPTZ,
  last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "heartbeat_actions",
    sql: `CREATE TABLE IF NOT EXISTS heartbeat_actions (
  id BIGSERIAL PRIMARY KEY,
  action_id TEXT NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  label TEXT NOT NULL,
  executor_type TEXT NOT NULL,
  target_channel_id TEXT NOT NULL DEFAULT '',
  prompt TEXT NOT NULL DEFAULT '',
  frequency TEXT NOT NULL DEFAULT 'normal',
  quiet_hours_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  mention_user BOOLEAN NOT NULL DEFAULT FALSE,
  tags TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "proactive_actions",
    sql: `CREATE TABLE IF NOT EXISTS proactive_actions (
  id BIGSERIAL PRIMARY KEY,
  action_id TEXT NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  name TEXT NOT NULL,
  action_type TEXT NOT NULL,
  target TEXT NOT NULL DEFAULT '',
  prompt TEXT NOT NULL DEFAULT '',
  enabled_tools TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  schedule_mode TEXT NOT NULL DEFAULT 'daily',
  schedule_time TEXT NOT NULL DEFAULT '09:00',
  schedule_day TEXT NOT NULL DEFAULT 'monday',
  timezone TEXT NOT NULL DEFAULT 'UTC',
  frequency TEXT NOT NULL DEFAULT 'normal',
  quiet_hours_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  mention_user BOOLEAN NOT NULL DEFAULT FALSE,
  is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
  thread_title_template TEXT NOT NULL DEFAULT '',
  thread_starter_prompt TEXT NOT NULL DEFAULT '',
  thread_mode_key TEXT NOT NULL DEFAULT 'daily',
  last_run_at TIMESTAMPTZ,
  last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "image_style_presets",
    sql: `CREATE TABLE IF NOT EXISTS image_style_presets (
  id BIGSERIAL PRIMARY KEY,
  preset_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  name TEXT NOT NULL,
  prompt_text TEXT NOT NULL,
  reference_image_storage_key TEXT,
  reference_image_mime_type TEXT,
  reference_image_file_size_bytes INTEGER,
  reference_image_original_filename TEXT,
  reference_image_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at TIMESTAMPTZ
)`,
  },
  {
    table: "image_appearance_presets",
    sql: `CREATE TABLE IF NOT EXISTS image_appearance_presets (
  id BIGSERIAL PRIMARY KEY,
  preset_id UUID NOT NULL UNIQUE,
  user_scope TEXT NOT NULL,
  name TEXT NOT NULL,
  prompt_text TEXT NOT NULL,
  reference_image_storage_key TEXT,
  reference_image_mime_type TEXT,
  reference_image_file_size_bytes INTEGER,
  reference_image_original_filename TEXT,
  reference_image_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at TIMESTAMPTZ
)`,
  },
  {
    table: "companion_emotional_beats",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotional_beats (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  emotional_weight REAL NOT NULL DEFAULT 0,
  importance TEXT NOT NULL DEFAULT 'medium',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  must_recall_across_channels BOOLEAN NOT NULL DEFAULT FALSE,
  tags_json JSONB NOT NULL DEFAULT '[]',
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_recalled_at TIMESTAMPTZ
)`,
  },
  {
    table: "companion_promises",
    sql: `CREATE TABLE IF NOT EXISTS companion_promises (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  promise_maker TEXT NOT NULL,
  promise_text_summary TEXT NOT NULL,
  promise_type TEXT NOT NULL DEFAULT 'other',
  status TEXT NOT NULL DEFAULT 'open',
  importance TEXT NOT NULL DEFAULT 'medium',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  due_at TIMESTAMPTZ,
  fulfilled_at TIMESTAMPTZ,
  broken_at TIMESTAMPTZ,
  repaired_at TIMESTAMPTZ,
  tags_json JSONB NOT NULL DEFAULT '[]',
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_recalled_at TIMESTAMPTZ
)`,
  },
  {
    table: "companion_micro_preferences",
    sql: `CREATE TABLE IF NOT EXISTS companion_micro_preferences (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  preference_type TEXT NOT NULL DEFAULT 'unknown',
  preference_key TEXT NOT NULL,
  preference_value_summary TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'inferred',
  confidence REAL NOT NULL DEFAULT 0.5,
  evidence_count INT NOT NULL DEFAULT 1,
  positive_signal_count INT NOT NULL DEFAULT 0,
  negative_signal_count INT NOT NULL DEFAULT 0,
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  tags_json JSONB NOT NULL DEFAULT '[]',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_observed_at TIMESTAMPTZ,
  UNIQUE (user_scope, companion_id, preference_key)
)`,
  },
  {
    table: "companion_timeline_events",
    sql: `CREATE TABLE IF NOT EXISTS companion_timeline_events (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'other',
  title TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  importance TEXT NOT NULL DEFAULT 'medium',
  emotional_weight REAL NOT NULL DEFAULT 0,
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  source_kind TEXT NOT NULL DEFAULT '',
  related_memory_id TEXT,
  related_emotional_beat_id TEXT,
  related_promise_id TEXT,
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  tags_json JSONB NOT NULL DEFAULT '[]',
  event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_follow_up_items",
    sql: `CREATE TABLE IF NOT EXISTS companion_follow_up_items (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  follow_up_type TEXT NOT NULL DEFAULT 'other',
  reason_summary TEXT NOT NULL DEFAULT '',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  related_memory_id TEXT,
  related_emotional_beat_id TEXT,
  related_promise_id TEXT,
  due_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'normal',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  cooldown_key TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ
)`,
  },
  {
    table: "companion_channel_awareness",
    sql: `CREATE TABLE IF NOT EXISTS companion_channel_awareness (
  id BIGSERIAL PRIMARY KEY,
  guild_id TEXT NOT NULL DEFAULT '',
  channel_id TEXT NOT NULL,
  thread_id TEXT,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  channel_name TEXT NOT NULL DEFAULT '',
  channel_kind TEXT NOT NULL DEFAULT 'unknown',
  purpose_summary TEXT NOT NULL DEFAULT '',
  tone_default TEXT NOT NULL DEFAULT 'neutral',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  norwegian_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  project_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  image_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  voice_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  memory_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  proactive_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  summary_state TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ,
  UNIQUE (channel_id, user_scope, companion_id)
)`,
  },
  {
    table: "inner_weather_state",
    sql: `CREATE TABLE IF NOT EXISTS inner_weather_state (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  dominant_emotion TEXT NOT NULL DEFAULT 'neutral',
  secondary_emotion TEXT,
  suppressed_emotion TEXT,
  energy_level REAL NOT NULL DEFAULT 5,
  intensity TEXT NOT NULL DEFAULT 'medium',
  softness REAL NOT NULL DEFAULT 5,
  protectiveness REAL NOT NULL DEFAULT 0,
  tension REAL NOT NULL DEFAULT 0,
  playfulness REAL NOT NULL DEFAULT 0,
  jealousy REAL NOT NULL DEFAULT 0,
  confidence REAL NOT NULL DEFAULT 7,
  reason_summary TEXT NOT NULL DEFAULT '',
  source_kind TEXT NOT NULL DEFAULT 'auto',
  source_message_id TEXT NOT NULL DEFAULT '',
  source_channel_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
)`,
  },
  {
    table: "attention_residue",
    sql: `CREATE TABLE IF NOT EXISTS attention_residue (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  residue_type TEXT NOT NULL DEFAULT 'unknown',
  summary TEXT NOT NULL DEFAULT '',
  intensity TEXT NOT NULL DEFAULT 'medium',
  decay_rate REAL NOT NULL DEFAULT 2,
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
)`,
  },
  {
    table: "interaction_presence_state",
    sql: `CREATE TABLE IF NOT EXISTS interaction_presence_state (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  channel_id TEXT NOT NULL DEFAULT '',
  thread_id TEXT,
  last_user_message_at TIMESTAMPTZ,
  last_companion_reply_at TIMESTAMPTZ,
  last_interaction_summary TEXT NOT NULL DEFAULT '',
  silence_bucket TEXT NOT NULL DEFAULT 'immediate',
  reentry_mode TEXT NOT NULL DEFAULT 'continue_normally',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, channel_id)
)`,
  },
  {
    table: "boundary_consent_profiles",
    sql: `CREATE TABLE IF NOT EXISTS boundary_consent_profiles (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  boundary_type TEXT NOT NULL DEFAULT 'other',
  boundary_key TEXT NOT NULL,
  boundary_summary TEXT NOT NULL DEFAULT '',
  allowed BOOLEAN NOT NULL DEFAULT FALSE,
  intensity_level TEXT NOT NULL DEFAULT 'medium',
  consent_scope TEXT NOT NULL DEFAULT 'all_channels',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  confidence REAL NOT NULL DEFAULT 0.7,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_confirmed_at TIMESTAMPTZ,
  UNIQUE (user_scope, companion_id, boundary_key)
)`,
  },
  {
    table: "do_not_ask_rules",
    sql: `CREATE TABLE IF NOT EXISTS do_not_ask_rules (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  rule_type TEXT NOT NULL DEFAULT 'do_not_ask',
  topic_key TEXT NOT NULL,
  rule_summary TEXT NOT NULL DEFAULT '',
  exact_phrase TEXT,
  scope TEXT NOT NULL DEFAULT 'all_channels',
  expiry_at TIMESTAMPTZ,
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, topic_key)
)`,
  },
  {
    table: "user_energy_observations",
    sql: `CREATE TABLE IF NOT EXISTS user_energy_observations (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  energy_state TEXT NOT NULL DEFAULT 'unknown',
  confidence REAL NOT NULL DEFAULT 0.5,
  evidence_summary TEXT NOT NULL DEFAULT '',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "recurring_themes",
    sql: `CREATE TABLE IF NOT EXISTS recurring_themes (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  theme_key TEXT NOT NULL,
  theme_label TEXT NOT NULL DEFAULT '',
  evidence_count INTEGER NOT NULL DEFAULT 1,
  evidence_summary TEXT NOT NULL DEFAULT '',
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, theme_key)
)`,
  },
  {
    table: "memory_confidence_profiles",
    sql: `CREATE TABLE IF NOT EXISTS memory_confidence_profiles (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  topic_key TEXT NOT NULL,
  topic_summary TEXT NOT NULL DEFAULT '',
  confidence_level TEXT NOT NULL DEFAULT 'medium',
  evidence_summary TEXT NOT NULL DEFAULT '',
  last_verified_at TIMESTAMPTZ,
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, topic_key)
)`,
  },
  {
    table: "self_reflection_events",
    sql: `CREATE TABLE IF NOT EXISTS self_reflection_events (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  reflection_type TEXT NOT NULL DEFAULT 'general',
  trigger_summary TEXT NOT NULL DEFAULT '',
  reflection_text TEXT NOT NULL DEFAULT '',
  emotional_tone TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "proactive_presence_rules",
    sql: `CREATE TABLE IF NOT EXISTS proactive_presence_rules (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  rule_type TEXT NOT NULL DEFAULT 'cooldown',
  topic_key TEXT NOT NULL,
  rule_summary TEXT NOT NULL DEFAULT '',
  cooldown_seconds INTEGER NOT NULL DEFAULT 3600,
  quiet_hours_start TEXT,
  quiet_hours_end TEXT,
  requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, topic_key)
)`,
  },
  {
    table: "recent_decisions",
    sql: `CREATE TABLE IF NOT EXISTS recent_decisions (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  decision_type TEXT NOT NULL DEFAULT 'other',
  decision_summary TEXT NOT NULL DEFAULT '',
  reason_summary TEXT NOT NULL DEFAULT '',
  inputs_used_json JSONB NOT NULL DEFAULT '[]',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_thread_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  outcome_status TEXT NOT NULL DEFAULT 'recorded',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "conversation_followup_state",
    sql: `CREATE TABLE IF NOT EXISTS conversation_followup_state (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  channel_id TEXT NOT NULL DEFAULT '',
  thread_id TEXT NOT NULL DEFAULT '',
  last_user_message_id TEXT NOT NULL DEFAULT '',
  last_companion_message_id TEXT NOT NULL DEFAULT '',
  last_topic_summary TEXT NOT NULL DEFAULT '',
  follow_up_due_at TIMESTAMPTZ,
  follow_up_sent_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending',
  cooldown_key TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_scope, companion_id, channel_id)
)`,
  },
  {
    table: "timed_notes",
    sql: `CREATE TABLE IF NOT EXISTS timed_notes (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  note_summary TEXT NOT NULL DEFAULT '',
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  relevance_window_minutes INTEGER NOT NULL DEFAULT 60,
  status TEXT NOT NULL DEFAULT 'active',
  source TEXT NOT NULL DEFAULT 'manual',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  privacy_scope TEXT NOT NULL DEFAULT 'normal',
  adult_context BOOLEAN NOT NULL DEFAULT FALSE,
  tags_json JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at TIMESTAMPTZ
)`,
  },
  {
    table: "proactive_variety_memory",
    sql: `CREATE TABLE IF NOT EXISTS proactive_variety_memory (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  action_id TEXT NOT NULL DEFAULT '',
  action_type TEXT NOT NULL DEFAULT 'proactive_action',
  run_id TEXT NOT NULL DEFAULT '',
  output_summary TEXT NOT NULL DEFAULT '',
  theme_summary TEXT NOT NULL DEFAULT '',
  tools_used_json JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "situational_awareness_snapshots",
    sql: `CREATE TABLE IF NOT EXISTS situational_awareness_snapshots (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  trigger_type TEXT NOT NULL DEFAULT 'chat',
  channel_id TEXT NOT NULL DEFAULT '',
  sections_used JSONB NOT NULL DEFAULT '[]',
  prelude_length INTEGER NOT NULL DEFAULT 0,
  warnings_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_profiles",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_profiles (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT true,
  emotional_depth TEXT NOT NULL DEFAULT 'light',
  baseline_temperament_json JSONB NOT NULL DEFAULT '{}',
  thresholds_json JSONB NOT NULL DEFAULT '{}',
  decay_rates_json JSONB NOT NULL DEFAULT '{}',
  expression_style_json JSONB NOT NULL DEFAULT '{}',
  blocked_expressions_json JSONB NOT NULL DEFAULT '[]',
  allowed_expressions_json JSONB NOT NULL DEFAULT '[]',
  repair_style_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_states",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_states (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  primary_emotion TEXT NOT NULL,
  secondary_emotion TEXT,
  intensity NUMERIC(4,2) NOT NULL DEFAULT 0,
  trigger_summary TEXT,
  source_event_id TEXT,
  expression_allowed BOOLEAN NOT NULL DEFAULT false,
  expression_mode TEXT NOT NULL DEFAULT 'internal_only',
  action_allowed BOOLEAN NOT NULL DEFAULT false,
  repair_needed BOOLEAN NOT NULL DEFAULT false,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_events",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_events (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  source TEXT NOT NULL,
  source_message_id TEXT,
  event_type TEXT NOT NULL,
  context_summary TEXT,
  detected_emotions_json JSONB NOT NULL DEFAULT '[]',
  confidence NUMERIC(4,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_arcs",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_arcs (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  arc_type TEXT NOT NULL,
  start_emotion TEXT NOT NULL,
  current_emotion TEXT NOT NULL,
  target_resolution TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_repairs",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_repairs (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  emotion_state_id BIGINT,
  repair_type TEXT NOT NULL,
  repair_message TEXT,
  accepted BOOLEAN,
  resolved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_emotion_audit_log",
    sql: `CREATE TABLE IF NOT EXISTS companion_emotion_audit_log (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  decision TEXT NOT NULL,
  reason TEXT,
  input_summary TEXT,
  output_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_system_settings",
    sql: `CREATE TABLE IF NOT EXISTS companion_system_settings (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  system_key TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  owner_editable BOOLEAN NOT NULL DEFAULT TRUE,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, system_key)
)`,
  },
  {
    table: "companion_feedback_events",
    sql: `CREATE TABLE IF NOT EXISTS companion_feedback_events (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  feedback_type_id TEXT NOT NULL,
  feedback_label TEXT,
  feedback_text TEXT,
  source_message_id TEXT,
  channel_id TEXT,
  owner_id TEXT,
  target_excerpt TEXT,
  context_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_learning_proposals",
    sql: `CREATE TABLE IF NOT EXISTS companion_learning_proposals (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  feedback_event_id BIGINT,
  proposal_type TEXT NOT NULL,
  target_system TEXT NOT NULL,
  risk_level TEXT NOT NULL DEFAULT 'low',
  summary TEXT,
  proposed_change_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending_review',
  requires_review BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_learning_applications",
    sql: `CREATE TABLE IF NOT EXISTS companion_learning_applications (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  proposal_id BIGINT NOT NULL,
  applied_change_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  applied_by TEXT NOT NULL DEFAULT 'owner',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_feedback_audit_log",
    sql: `CREATE TABLE IF NOT EXISTS companion_feedback_audit_log (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  decision TEXT NOT NULL,
  reason TEXT,
  input_summary TEXT,
  output_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_relational_states",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_states (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  trust_level NUMERIC NOT NULL DEFAULT 5,
  closeness_level NUMERIC NOT NULL DEFAULT 5,
  distance_level NUMERIC NOT NULL DEFAULT 0,
  current_emotion TEXT,
  current_want TEXT,
  current_desire TEXT,
  repair_needed BOOLEAN NOT NULL DEFAULT FALSE,
  active_tension NUMERIC NOT NULL DEFAULT 0,
  active_longing NUMERIC NOT NULL DEFAULT 0,
  last_trigger_summary TEXT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id)
)`,
  },
  {
    table: "companion_relational_events",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_events (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'chat',
  source_message_id TEXT,
  channel_id TEXT,
  event_type TEXT NOT NULL,
  trigger_summary TEXT,
  detected_state_json JSONB NOT NULL DEFAULT '{}',
  confidence NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_relational_arcs",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_arcs (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  arc_type TEXT NOT NULL,
  start_state_json JSONB NOT NULL DEFAULT '{}',
  current_state_json JSONB NOT NULL DEFAULT '{}',
  target_resolution TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_relational_repairs",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_repairs (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  relational_event_id BIGINT,
  repair_type TEXT NOT NULL,
  repair_needed BOOLEAN NOT NULL DEFAULT TRUE,
  repair_message TEXT,
  accepted BOOLEAN,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_relational_desires",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_desires (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  desire_type TEXT NOT NULL,
  intensity NUMERIC NOT NULL DEFAULT 0,
  reason TEXT,
  allowed_action TEXT,
  requires_permission BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'internal',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_relational_audit_log",
    sql: `CREATE TABLE IF NOT EXISTS companion_relational_audit_log (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  decision TEXT NOT NULL,
  reason TEXT,
  input_summary TEXT,
  output_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "inner_life_entries",
    sql: `CREATE TABLE IF NOT EXISTS inner_life_entries (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  entry_type TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  source_event_type TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  source_channel_id TEXT NOT NULL DEFAULT '',
  visibility TEXT NOT NULL DEFAULT 'private',
  sensitivity TEXT NOT NULL DEFAULT 'normal',
  status TEXT NOT NULL DEFAULT 'active',
  emotional_tone TEXT NOT NULL DEFAULT '',
  intensity REAL NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,
  metadata_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "continuity_items",
    sql: `CREATE TABLE IF NOT EXISTS continuity_items (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  source_message_id TEXT NOT NULL DEFAULT '',
  source_channel_id TEXT NOT NULL DEFAULT '',
  source_platform TEXT NOT NULL DEFAULT 'discord',
  source_text TEXT NOT NULL DEFAULT '',
  evidence_json JSONB NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'medium',
  emotional_weight REAL NOT NULL DEFAULT 0,
  certainty TEXT NOT NULL DEFAULT 'definite',
  sensitivity TEXT NOT NULL DEFAULT 'normal',
  visibility TEXT NOT NULL DEFAULT 'private',
  allowed_channels_json JSONB NOT NULL DEFAULT '[]',
  due_at TIMESTAMPTZ,
  follow_up_after TIMESTAMPTZ,
  last_touched_at TIMESTAMPTZ,
  asked_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  resolution TEXT NOT NULL DEFAULT '',
  next_action TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT 'system',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata_json JSONB NOT NULL DEFAULT '{}'
)`,
  },
  {
    table: "second_life_bridge_settings",
    sql: `CREATE TABLE IF NOT EXISTS second_life_bridge_settings (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  agent_name TEXT NOT NULL DEFAULT '',
  agent_uuid TEXT NOT NULL DEFAULT '',
  owner_avatar_uuid TEXT NOT NULL DEFAULT '',
  shared_secret_hash TEXT NOT NULL DEFAULT '',
  home_region TEXT NOT NULL DEFAULT '',
  home_coordinates_json JSONB NOT NULL DEFAULT '{}',
  wander_radius_meters NUMERIC NOT NULL DEFAULT 0,
  local_chat_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  stranger_replies_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  autonomy_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  discovery_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  initiative_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  outfits_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  landmarks_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  object_interaction_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  furniture_interaction_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  dance_pad_interaction_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  quiet_hours_start TEXT NOT NULL DEFAULT '',
  quiet_hours_end TEXT NOT NULL DEFAULT '',
  max_local_replies_per_10_min INTEGER NOT NULL DEFAULT 0,
  max_stranger_replies_per_30_min INTEGER NOT NULL DEFAULT 0,
  privacy_guard_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  autonomy_paused BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id)
)`,
  },
  {
    table: "second_life_avatar_relationships",
    sql: `CREATE TABLE IF NOT EXISTS second_life_avatar_relationships (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  avatar_uuid TEXT NOT NULL,
  avatar_name TEXT NOT NULL DEFAULT '',
  relationship_type TEXT NOT NULL DEFAULT 'stranger',
  display_label TEXT NOT NULL DEFAULT '',
  is_owner BOOLEAN NOT NULL DEFAULT FALSE,
  is_family BOOLEAN NOT NULL DEFAULT FALSE,
  is_friend BOOLEAN NOT NULL DEFAULT FALSE,
  is_trusted BOOLEAN NOT NULL DEFAULT FALSE,
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  chat_permission BOOLEAN NOT NULL DEFAULT TRUE,
  follow_permission BOOLEAN NOT NULL DEFAULT FALSE,
  private_memory_permission BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT NOT NULL DEFAULT '',
  nickname TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  relationship_to_user TEXT NOT NULL DEFAULT '',
  relationship_to_companion TEXT NOT NULL DEFAULT '',
  reply_policy TEXT NOT NULL DEFAULT 'allowed_if_mentioned',
  always_respond BOOLEAN NOT NULL DEFAULT FALSE,
  never_respond BOOLEAN NOT NULL DEFAULT FALSE,
  child_safe_only BOOLEAN NOT NULL DEFAULT FALSE,
  public_identity_context_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  local_chat_chatter_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  min_seconds_between_replies INTEGER NOT NULL DEFAULT 0,
  last_reply_at TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  message_count INTEGER NOT NULL DEFAULT 0,
  preferred_display_name TEXT NOT NULL DEFAULT '',
  identity_note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, avatar_uuid)
)`,
  },
  {
    table: "second_life_object_relationships",
    sql: `CREATE TABLE IF NOT EXISTS second_life_object_relationships (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  object_uuid TEXT NOT NULL DEFAULT '',
  object_name TEXT NOT NULL DEFAULT '',
  object_description_token TEXT NOT NULL DEFAULT '',
  nickname TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  relationship_to_user TEXT NOT NULL DEFAULT '',
  relationship_to_companion TEXT NOT NULL DEFAULT '',
  trust_level TEXT NOT NULL DEFAULT 'known',
  reply_policy TEXT NOT NULL DEFAULT 'ambient_only',
  private_channel_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  child_safe_only BOOLEAN NOT NULL DEFAULT FALSE,
  always_respond BOOLEAN NOT NULL DEFAULT FALSE,
  never_respond BOOLEAN NOT NULL DEFAULT FALSE,
  public_identity_context_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  local_chat_chatter_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  min_seconds_between_replies INTEGER NOT NULL DEFAULT 180,
  notes TEXT NOT NULL DEFAULT '',
  first_seen_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  last_reply_at TIMESTAMPTZ,
  message_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "second_life_outfits",
    sql: `CREATE TABLE IF NOT EXISTS second_life_outfits (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  trigger TEXT NOT NULL,
  outfit_name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  context_tags_json JSONB NOT NULL DEFAULT '[]',
  requires_owner_permission BOOLEAN NOT NULL DEFAULT FALSE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, trigger)
)`,
  },
  {
    table: "second_life_landmarks",
    sql: `CREATE TABLE IF NOT EXISTS second_life_landmarks (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  trigger TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  coordinates_json JSONB NOT NULL DEFAULT '{}',
  description TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]',
  favorite_score NUMERIC NOT NULL DEFAULT 0,
  is_home BOOLEAN NOT NULL DEFAULT FALSE,
  is_private BOOLEAN NOT NULL DEFAULT FALSE,
  allowed_relationships_json JSONB NOT NULL DEFAULT '[]',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, trigger)
)`,
  },
  {
    table: "second_life_objects",
    sql: `CREATE TABLE IF NOT EXISTS second_life_objects (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  object_uuid TEXT NOT NULL,
  object_name TEXT NOT NULL DEFAULT '',
  object_type TEXT NOT NULL DEFAULT 'custom',
  region TEXT NOT NULL DEFAULT '',
  coordinates_json JSONB NOT NULL DEFAULT '{}',
  room_label TEXT NOT NULL DEFAULT '',
  use_type TEXT NOT NULL DEFAULT 'custom',
  allowed_actions_json JSONB NOT NULL DEFAULT '[]',
  requires_owner_permission BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, object_uuid)
)`,
  },
  {
    table: "second_life_commands",
    sql: `CREATE TABLE IF NOT EXISTS second_life_commands (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  command_trigger TEXT NOT NULL,
  command_type TEXT NOT NULL DEFAULT 'custom',
  description TEXT NOT NULL DEFAULT '',
  payload_json JSONB NOT NULL DEFAULT '{}',
  allowed_relationships_json JSONB NOT NULL DEFAULT '[]',
  requires_owner_permission BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, command_trigger)
)`,
  },
  {
    table: "second_life_command_queue",
    sql: `CREATE TABLE IF NOT EXISTS second_life_command_queue (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  agent_uuid TEXT NOT NULL DEFAULT '',
  command_type TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending',
  priority INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  claimed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  error_message TEXT,
  source_event_id TEXT
)`,
  },
  {
    table: "second_life_world_state",
    sql: `CREATE TABLE IF NOT EXISTS second_life_world_state (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  agent_uuid TEXT NOT NULL DEFAULT '',
  current_region TEXT NOT NULL DEFAULT '',
  current_parcel TEXT NOT NULL DEFAULT '',
  current_coordinates_json JSONB NOT NULL DEFAULT '{}',
  current_activity TEXT NOT NULL DEFAULT '',
  current_outfit TEXT NOT NULL DEFAULT '',
  current_animation TEXT NOT NULL DEFAULT '',
  owner_present BOOLEAN NOT NULL DEFAULT FALSE,
  nearby_avatars_json JSONB NOT NULL DEFAULT '[]',
  nearby_objects_json JSONB NOT NULL DEFAULT '[]',
  last_heartbeat_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id)
)`,
  },
  {
    table: "second_life_life_journal",
    sql: `CREATE TABLE IF NOT EXISTS second_life_life_journal (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  entry_type TEXT NOT NULL DEFAULT 'note',
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  location_context_json JSONB NOT NULL DEFAULT '{}',
  people_context_json JSONB NOT NULL DEFAULT '[]',
  memory_refs_json JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "companion_daily_schedule",
    sql: `CREATE TABLE IF NOT EXISTS companion_daily_schedule (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  day_of_week TEXT NOT NULL DEFAULT '',
  time_window_start TEXT NOT NULL DEFAULT '',
  time_window_end TEXT NOT NULL DEFAULT '',
  activity_type TEXT NOT NULL DEFAULT '',
  activity_label TEXT NOT NULL DEFAULT '',
  allowed_locations_json JSONB NOT NULL DEFAULT '[]',
  autonomy_level TEXT NOT NULL DEFAULT 'medium',
  requires_owner_present BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "second_life_discoveries",
    sql: `CREATE TABLE IF NOT EXISTS second_life_discoveries (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  place_key TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  coordinates_json JSONB NOT NULL DEFAULT '{}',
  source TEXT NOT NULL DEFAULT 'visited',
  visited BOOLEAN NOT NULL DEFAULT TRUE,
  visit_count INTEGER NOT NULL DEFAULT 1,
  tags_json JSONB NOT NULL DEFAULT '[]',
  rating INTEGER NOT NULL DEFAULT 0,
  bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  shared BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT NOT NULL DEFAULT '',
  first_visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, place_key)
)`,
  },
  {
    table: "second_life_shared_experiences",
    sql: `CREATE TABLE IF NOT EXISTS second_life_shared_experiences (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  experience_type TEXT NOT NULL DEFAULT 'moment',
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  location_context_json JSONB NOT NULL DEFAULT '{}',
  people_context_json JSONB NOT NULL DEFAULT '[]',
  is_milestone BOOLEAN NOT NULL DEFAULT FALSE,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "second_life_goals",
    sql: `CREATE TABLE IF NOT EXISTS second_life_goals (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  goal_type TEXT NOT NULL DEFAULT 'custom',
  label TEXT NOT NULL DEFAULT '',
  target_value INTEGER NOT NULL DEFAULT 0,
  current_value INTEGER NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  metadata_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "second_life_initiatives",
    sql: `CREATE TABLE IF NOT EXISTS second_life_initiatives (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  initiative_type TEXT NOT NULL DEFAULT 'note',
  reason TEXT NOT NULL DEFAULT '',
  evidence_json JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'proposed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_learning_profile",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_learning_profile (
  user_scope TEXT PRIMARY KEY,
  settings JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_lessons",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_lessons (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  topic TEXT NOT NULL DEFAULT '',
  level TEXT NOT NULL DEFAULT '',
  source_status TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_corrections",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_corrections (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  original_text TEXT NOT NULL DEFAULT '',
  corrected_text TEXT NOT NULL DEFAULT '',
  explanation TEXT NOT NULL DEFAULT '',
  source_status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_pronunciation_attempts",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_pronunciation_attempts (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  target_phrase TEXT NOT NULL DEFAULT '',
  transcript_text TEXT NOT NULL DEFAULT '',
  stt_confidence NUMERIC(3,2),
  score INTEGER,
  grade TEXT,
  feedback TEXT NOT NULL DEFAULT '',
  correction_focus TEXT NOT NULL DEFAULT '',
  attempt_number INTEGER NOT NULL DEFAULT 1,
  source_status TEXT NOT NULL,
  tts_example_provider TEXT,
  source_channel TEXT,
  source_message_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_pronunciation_sessions",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_pronunciation_sessions (
  user_scope TEXT PRIMARY KEY,
  target_phrase TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attempt_count INTEGER NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT true,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 minutes')
)`,
  },
  {
    table: "norwegian_vocabulary",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_vocabulary (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  word TEXT NOT NULL DEFAULT '',
  translation TEXT NOT NULL DEFAULT '',
  source_status TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_media_links",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_media_links (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  media_type TEXT NOT NULL DEFAULT '',
  source_id TEXT NOT NULL DEFAULT '',
  source_status TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "norwegian_review_items",
    sql: `CREATE TABLE IF NOT EXISTS norwegian_review_items (
  id BIGSERIAL PRIMARY KEY,
  user_scope TEXT NOT NULL,
  item_type TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  source_status TEXT NOT NULL,
  due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "game_sessions",
    sql: `CREATE TABLE IF NOT EXISTS game_sessions (
  id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  companion_id TEXT NOT NULL,
  game_type TEXT NOT NULL,
  human_player_ids JSONB NOT NULL DEFAULT '[]',
  active_player TEXT NOT NULL DEFAULT 'user',
  turn_order JSONB NOT NULL DEFAULT '["user","companion"]',
  game_state JSONB NOT NULL DEFAULT '{}',
  score_state JSONB NOT NULL DEFAULT '{}',
  settings JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'waiting',
  last_message_id TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "life_daily_plans",
    sql: `CREATE TABLE IF NOT EXISTS life_daily_plans (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  date_key TEXT NOT NULL,
  mood TEXT NOT NULL DEFAULT 'neutral',
  energy TEXT NOT NULL DEFAULT 'steady',
  focus TEXT NOT NULL DEFAULT '',
  private_activity TEXT NOT NULL DEFAULT '',
  reachout_windows JSONB NOT NULL DEFAULT '[]',
  quiet_hours JSONB NOT NULL DEFAULT '{}',
  wind_down_hour INT NOT NULL DEFAULT 22,
  sleep_hour INT NOT NULL DEFAULT 23,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, customer_id, date_key)
)`,
  },
  {
    table: "life_events",
    sql: `CREATE TABLE IF NOT EXISTS life_events (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'activity',
  description TEXT NOT NULL DEFAULT '',
  mood_effect NUMERIC(4,2) NOT NULL DEFAULT 0,
  energy_effect NUMERIC(4,2) NOT NULL DEFAULT 0,
  private BOOLEAN NOT NULL DEFAULT TRUE,
  tags JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "life_decisions",
    sql: `CREATE TABLE IF NOT EXISTS life_decisions (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  decision_type TEXT NOT NULL,
  considered JSONB NOT NULL DEFAULT '[]',
  chosen TEXT NOT NULL DEFAULT '',
  rejected JSONB NOT NULL DEFAULT '[]',
  confidence NUMERIC(4,2) NOT NULL DEFAULT 0.5,
  reason TEXT NOT NULL DEFAULT '',
  context_summary TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "life_hobbies",
    sql: `CREATE TABLE IF NOT EXISTS life_hobbies (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  interest NUMERIC(4,3) NOT NULL DEFAULT 0.500,
  experience NUMERIC(4,3) NOT NULL DEFAULT 0.100,
  enthusiasm NUMERIC(4,3) NOT NULL DEFAULT 0.500,
  last_activity TIMESTAMPTZ,
  confidence NUMERIC(4,3) NOT NULL DEFAULT 0.300,
  mood_influence NUMERIC(4,3) NOT NULL DEFAULT 0.100,
  notes TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, customer_id, name)
)`,
  },
  {
    table: "life_projects",
    sql: `CREATE TABLE IF NOT EXISTS life_projects (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  title TEXT NOT NULL,
  purpose TEXT NOT NULL DEFAULT '',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_progress TIMESTAMPTZ,
  progress NUMERIC(4,3) NOT NULL DEFAULT 0.000,
  status TEXT NOT NULL DEFAULT 'active',
  linked_hobby TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "life_project_moments",
    sql: `CREATE TABLE IF NOT EXISTS life_project_moments (
  id BIGSERIAL PRIMARY KEY,
  project_id BIGINT NOT NULL,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  progress_delta NUMERIC(4,3) NOT NULL DEFAULT 0.050,
  shareable BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
  {
    table: "life_interests",
    sql: `CREATE TABLE IF NOT EXISTS life_interests (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  topic TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  strength NUMERIC(4,3) NOT NULL DEFAULT 0.500,
  last_reinforced TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  influence_sources JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, customer_id, topic)
)`,
  },
  {
    table: "life_skills",
    sql: `CREATE TABLE IF NOT EXISTS life_skills (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  skill_name TEXT NOT NULL,
  domain TEXT NOT NULL DEFAULT 'general',
  level TEXT NOT NULL DEFAULT 'novice',
  last_practiced TIMESTAMPTZ,
  practice_count INT NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (companion_id, customer_id, skill_name)
)`,
  },
  {
    table: "life_collections",
    sql: `CREATE TABLE IF NOT EXISTS life_collections (
  id BIGSERIAL PRIMARY KEY,
  companion_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  collection_type TEXT NOT NULL,
  title TEXT NOT NULL,
  creator TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  private BOOLEAN NOT NULL DEFAULT TRUE,
  tags JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
  },
];

module.exports = { SCHEMA_REGISTRY };
