"use strict";
const { execSync } = require("node:child_process");
const { getRuntimeState, mask } = require("./runtimeState");
function safe(v, fallback="unknown"){ return v === undefined || v === null || v === "" ? fallback : v; }
function getCommit(){ try { return execSync("git rev-parse --short HEAD", { cwd: process.cwd(), stdio:["ignore","pipe","ignore"] }).toString().trim(); } catch { return "unknown"; } }
function getSystemTruthSnapshot({ appContext = {}, client = appContext.client } = {}) {
  const config = appContext.config || {}; const st = getRuntimeState();
  const snapshot = {
    runtime: { environment: safe(config.nodeEnv || process.env.NODE_ENV), activeCompanionId: safe(config.memory?.companionId || config.companion?.id, "unknown"), activeUserScope: safe(config.memory?.userScope, "unknown"), productionRuntimePath: "artifacts/ghostlight-bot/src", discordBotConnected: Boolean(client?.isReady?.() || appContext.ready), deploymentCommit: getCommit(), uptimeSeconds: Math.floor(process.uptime()), lastStartupTime: st.startupAt },
    llm: { activeChatProvider: safe(st.llm.activeChatProvider || config.llm?.provider || "openai"), activeModel: safe(st.llm.activeModel || config.openai?.chatModel || config.llm?.chat?.model), adultModeModelOverride: safe(config.chat?.adultPrivateMode?.model, "not_configured"), fallbackModel: safe(config.openai?.fallbackModel || config.llm?.fallbackModel, "not_configured"), lastModelUsed: safe(st.llm.lastModelUsed), lastModelErrorSafeSummary: safe(st.llm.lastModelErrorSafeSummary, "unknown") },
    audio: { selectedAudioProvider: safe(config.audio?.provider || config.audio?.selectedProvider, "unknown"), fishAudioConfigured: Boolean(config.audio?.fishAudio?.apiKey || process.env.FISH_AUDIO_API_KEY), elevenLabsConfigured: Boolean(config.audio?.elevenLabs?.apiKey || process.env.ELEVENLABS_API_KEY), activeVoiceIdMasked: mask(config.audio?.voiceId || config.audio?.fishAudio?.voiceId || config.audio?.elevenLabs?.voiceId), lastGeneratedAudioProvider: safe(st.audio.lastGeneratedAudioProvider), lastAudioGenerationStatus: safe(st.audio.lastAudioGenerationStatus), lastAudioErrorSafeSummary: safe(st.audio.lastAudioErrorSafeSummary) },
    image: { imageGenerationEnabled: Boolean(config.images?.enabled || config.openai?.imageModel), activeImageProvider: safe(config.images?.provider || "openai"), activeModel: safe(config.openai?.imageModel || config.images?.model), selectedAppearancePreset: safe(st.image.selectedAppearancePreset), selectedStylePreset: safe(st.image.selectedStylePreset), lastImageGenerationStatus: safe(st.image.lastImageGenerationStatus), lastImageErrorSafeSummary: safe(st.image.lastImageErrorSafeSummary) },
    memory: { memoryBackendStatus: appContext.memoryStore?.available ? "configured" : "unknown", databaseConnected: Boolean(appContext.memoryStore?.available), qdrantConnected: safe(st.memory.qdrantConnected, "unknown"), lastMemorySaved: safe(st.memory.lastMemorySaved), lastEmotionalBeatSaved: safe(st.memory.lastEmotionalBeatSaved), lastMemoryRetrieval: safe(st.memory.lastMemoryRetrieval), lastCrossChannelRetrieval: safe(st.memory.lastCrossChannelRetrieval), lastContinuityPreludeBuilt: safe(st.memory.lastContinuityPreludeBuilt), memoryCurationEnabled: Boolean(appContext.generatedMemories) },
    qdrant: { qdrantEnabled: Boolean(config.qdrant?.url), qdrantUrlConfigured: Boolean(config.qdrant?.url), qdrantKeyConfigured: Boolean(config.qdrant?.apiKey), qdrantCollectionName: safe(config.qdrant?.collection, "ghostlight-memory"), qdrantUrlSafe: config.qdrant?.url ? String(config.qdrant.url).replace(/^https?:\/\//, "").replace(/:\d+.*$/, "") + "…" : "not_configured", qdrantConnected: safe(st.memory.qdrantConnected, "unknown"), qdrantLastCheck: safe(st.memory.qdrantLastCheck, "never"), qdrantLastError: safe(st.memory.qdrantLastError, "none"), qdrantLastSuccessfulSync: safe(st.memory.qdrantLastSuccessfulSync, "never"), qdrantIndexedCount: safe(st.memory.qdrantIndexedCount, "unknown") },
    continuity: { emotionalBeatsEnabled: Boolean(appContext.emotionalBeatStore), promiseLedgerEnabled: Boolean(appContext.promiseLedger), toneModeResolverEnabled: true, voiceFingerprintGuardEnabled: st.continuity.voiceFingerprintGuardEnabled !== false, relationshipRepairEngineEnabled: true, lastToneMode: safe(st.continuity.lastToneMode), lastVoiceGuardResult: safe(st.continuity.lastVoiceGuardResult), lastRepairEvent: safe(st.continuity.lastRepairEvent) },
    norwegian: { norwegianModeEnabled: Boolean(appContext.norwegianLearning), currentLevel: safe(st.norwegian.currentLevel), sourceCheckRequired: true, pronunciationCoachEnabled: Boolean(appContext.norwegianLearning), mediaCuratorEnabled: Boolean(appContext.norwegianLearning), reviewEngineEnabled: Boolean(appContext.norwegianLearning), masteryEngineEnabled: Boolean(appContext.norwegianLearning), lastNorwegianLearningEvent: safe(st.norwegian.lastNorwegianLearningEvent), lastSourceStatus: safe(st.norwegian.lastSourceStatus, "not_checked"), lastMediaLinkSaved: safe(st.norwegian.lastMediaLinkSaved) },
    privacy: { adultModeConfiguredChannel: mask(config.chat?.adultPrivateMode?.channelId), currentAdultModeActive: safe(st.privacy.currentAdultModeActive, "unknown"), privateAdultMemoryGatingEnabled: st.privacy.privateAdultMemoryGatingEnabled !== false, rawAudioStorageEnabled: Boolean(config.audio?.storeRawAudio), rawTranscriptLoggingEnabled: Boolean(config.logging?.rawTranscripts), safeErrorShieldEnabled: st.privacy.safeErrorShieldEnabled !== false },
    errors: { lastSafeUserFacingFallback: safe(st.errors.lastSafeUserFacingFallback), lastInternalErrorSafeCode: safe(st.errors.lastInternalErrorSafeCode), rawErrorLeakageBlockedCount: st.errors.rawErrorLeakageBlockedCount || 0, lastProviderRejectionHandled: safe(st.errors.lastProviderRejectionHandled), lastHighRiskRejectionHandled: safe(st.errors.lastHighRiskRejectionHandled) },
    generatedAt: new Date().toISOString(),
  };
  appContext.logger?.info?.(`[system-truth] snapshot generated sections=${Object.keys(snapshot).filter(k=>k!=="generatedAt").join(",")}`);
  return snapshot;
}
module.exports = { getSystemTruthSnapshot };
